name: pii_detection
services:
  backend:
    build:
      context: .
      dockerfile: deploy/backend-Dockerfile
    ports:
      - "5000:5000"
    env_file: .env
  ml:
    build:
      context: .
      dockerfile: deploy/ml-Dockerfile
    ports:
      - "5001:5001"
    env_file: .env