version: '3'
name: ai-datastack
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-03-15T01-07-19Z
  command: server --console-address ":9001" http://minio{1...2}/data{1...2}
  networks:
    - datastack-network
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ai231g1
      - POSTGRES_USER=ai231g1
      - POSTGRES_DB=pii_db
    networks:
      - datastack-network
  
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
  
  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
  
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    networks:
      - datastack-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:

networks:
  datastack-network:
    external: true
    name: datastack-network