version: '3'
name: backend_service
services:
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: python3 app.py
    networks:
      - datastack-network

networks:
  datastack-network:
    external: true
    name: datastack-network