name: CI for

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: 3.10

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Get DB secrets
              run: |
                echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
                echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
                echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
                echo "DB_PASS=${{ secrets.DB_PASS }}" >> $GITHUB_ENV

            - name: Get AWS secrets
              run: |
                echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
                echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
                echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> $GITHUB_ENV
            
            - name: Run Tests
              run: |
                  pytest